package com.vasiliskavrn.shop.web.entity;
// Generated Dec 11, 2016 2:21:03 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Color generated by hbm2java
 */
public class Color  implements java.io.Serializable {


     private int idColor;
     private String colName;
     private String colStatus;
     private Set goodses = new HashSet(0);

    public Color() {
    }

	
    public Color(int idColor) {
        this.idColor = idColor;
    }
    public Color(int idColor, String colName, String colStatus, Set goodses) {
       this.idColor = idColor;
       this.colName = colName;
       this.colStatus = colStatus;
       this.goodses = goodses;
    }
   
    public int getIdColor() {
        return this.idColor;
    }
    
    public void setIdColor(int idColor) {
        this.idColor = idColor;
    }
    public String getColName() {
        return this.colName;
    }
    
    public void setColName(String colName) {
        this.colName = colName;
    }
    public String getColStatus() {
        return this.colStatus;
    }
    
    public void setColStatus(String colStatus) {
        this.colStatus = colStatus;
    }
    public Set getGoodses() {
        return this.goodses;
    }
    
    public void setGoodses(Set goodses) {
        this.goodses = goodses;
    }




}


