package com.vasiliskavrn.shop.web.entity;
// Generated Dec 11, 2016 2:21:03 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Composition generated by hbm2java
 */
public class Composition  implements java.io.Serializable {


     private int idComp;
     private String compName;
     private String compStatus;
     private Set goodses = new HashSet(0);

    public Composition() {
    }

	
    public Composition(int idComp) {
        this.idComp = idComp;
    }
    public Composition(int idComp, String compName, String compStatus, Set goodses) {
       this.idComp = idComp;
       this.compName = compName;
       this.compStatus = compStatus;
       this.goodses = goodses;
    }
   
    public int getIdComp() {
        return this.idComp;
    }
    
    public void setIdComp(int idComp) {
        this.idComp = idComp;
    }
    public String getCompName() {
        return this.compName;
    }
    
    public void setCompName(String compName) {
        this.compName = compName;
    }
    public String getCompStatus() {
        return this.compStatus;
    }
    
    public void setCompStatus(String compStatus) {
        this.compStatus = compStatus;
    }
    public Set getGoodses() {
        return this.goodses;
    }
    
    public void setGoodses(Set goodses) {
        this.goodses = goodses;
    }




}


