package com.vasiliskavrn.shop.web.entity;
// Generated Dec 11, 2016 2:21:03 PM by Hibernate Tools 4.3.1



/**
 * Goods generated by hbm2java
 */
public class Goods  implements java.io.Serializable {


     private int goodsId;
     private Brand brand;
     private Cloth cloth;
     private Color color;
     private Composition composition;
     private Firme firme;
     private Image image;
     private Price price;
     private Producer producer;
     private Sex sex;
     private Size size;
     private String goodsArt;
     private String goodsStatus;

    public Goods() {
    }

	
    public Goods(int goodsId) {
        this.goodsId = goodsId;
    }
    public Goods(int goodsId, Brand brand, Cloth cloth, Color color, Composition composition, Firme firme, Image image, Price price, Producer producer, Sex sex, Size size, String goodsArt, String goodsStatus) {
       this.goodsId = goodsId;
       this.brand = brand;
       this.cloth = cloth;
       this.color = color;
       this.composition = composition;
       this.firme = firme;
       this.image = image;
       this.price = price;
       this.producer = producer;
       this.sex = sex;
       this.size = size;
       this.goodsArt = goodsArt;
       this.goodsStatus = goodsStatus;
    }
   
    public int getGoodsId() {
        return this.goodsId;
    }
    
    public void setGoodsId(int goodsId) {
        this.goodsId = goodsId;
    }
    public Brand getBrand() {
        return this.brand;
    }
    
    public void setBrand(Brand brand) {
        this.brand = brand;
    }
    public Cloth getCloth() {
        return this.cloth;
    }
    
    public void setCloth(Cloth cloth) {
        this.cloth = cloth;
    }
    public Color getColor() {
        return this.color;
    }
    
    public void setColor(Color color) {
        this.color = color;
    }
    public Composition getComposition() {
        return this.composition;
    }
    
    public void setComposition(Composition composition) {
        this.composition = composition;
    }
    public Firme getFirme() {
        return this.firme;
    }
    
    public void setFirme(Firme firme) {
        this.firme = firme;
    }
    public Image getImage() {
        return this.image;
    }
    
    public void setImage(Image image) {
        this.image = image;
    }
    public Price getPrice() {
        return this.price;
    }
    
    public void setPrice(Price price) {
        this.price = price;
    }
    public Producer getProducer() {
        return this.producer;
    }
    
    public void setProducer(Producer producer) {
        this.producer = producer;
    }
    public Sex getSex() {
        return this.sex;
    }
    
    public void setSex(Sex sex) {
        this.sex = sex;
    }
    public Size getSize() {
        return this.size;
    }
    
    public void setSize(Size size) {
        this.size = size;
    }
    public String getGoodsArt() {
        return this.goodsArt;
    }
    
    public void setGoodsArt(String goodsArt) {
        this.goodsArt = goodsArt;
    }
    public String getGoodsStatus() {
        return this.goodsStatus;
    }
    
    public void setGoodsStatus(String goodsStatus) {
        this.goodsStatus = goodsStatus;
    }




}


