package com.vasiliskavrn.shop.web.entity;
// Generated Dec 11, 2016 2:21:03 PM by Hibernate Tools 4.3.1



/**
 * Groups generated by hbm2java
 */
public class Groups  implements java.io.Serializable {


     private String groupid;

    public Groups() {
    }

    public Groups(String groupid) {
       this.groupid = groupid;
    }
   
    public String getGroupid() {
        return this.groupid;
    }
    
    public void setGroupid(String groupid) {
        this.groupid = groupid;
    }




}


