package com.vasiliskavrn.shop.web.entity;
// Generated Dec 11, 2016 2:21:03 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Image generated by hbm2java
 */
public class Image  implements java.io.Serializable {


     private int idImage;
     private byte[] imageCotnent;
     private String imageStatus;
     private Set goodses = new HashSet(0);

    public Image() {
    }

	
    public Image(int idImage) {
        this.idImage = idImage;
    }
    public Image(int idImage, byte[] imageCotnent, String imageStatus, Set goodses) {
       this.idImage = idImage;
       this.imageCotnent = imageCotnent;
       this.imageStatus = imageStatus;
       this.goodses = goodses;
    }
   
    public int getIdImage() {
        return this.idImage;
    }
    
    public void setIdImage(int idImage) {
        this.idImage = idImage;
    }
    public byte[] getImageCotnent() {
        return this.imageCotnent;
    }
    
    public void setImageCotnent(byte[] imageCotnent) {
        this.imageCotnent = imageCotnent;
    }
    public String getImageStatus() {
        return this.imageStatus;
    }
    
    public void setImageStatus(String imageStatus) {
        this.imageStatus = imageStatus;
    }
    public Set getGoodses() {
        return this.goodses;
    }
    
    public void setGoodses(Set goodses) {
        this.goodses = goodses;
    }




}


