package com.vasiliskavrn.shop.web.entity;
// Generated Dec 11, 2016 2:21:03 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Price generated by hbm2java
 */
public class Price  implements java.io.Serializable {


     private int idPrice;
     private Integer priceVal;
     private Date priceDate;
     private String priceStatus;
     private Set goodses = new HashSet(0);

    public Price() {
    }

	
    public Price(int idPrice) {
        this.idPrice = idPrice;
    }
    public Price(int idPrice, Integer priceVal, Date priceDate, String priceStatus, Set goodses) {
       this.idPrice = idPrice;
       this.priceVal = priceVal;
       this.priceDate = priceDate;
       this.priceStatus = priceStatus;
       this.goodses = goodses;
    }
   
    public int getIdPrice() {
        return this.idPrice;
    }
    
    public void setIdPrice(int idPrice) {
        this.idPrice = idPrice;
    }
    public Integer getPriceVal() {
        return this.priceVal;
    }
    
    public void setPriceVal(Integer priceVal) {
        this.priceVal = priceVal;
    }
    public Date getPriceDate() {
        return this.priceDate;
    }
    
    public void setPriceDate(Date priceDate) {
        this.priceDate = priceDate;
    }
    public String getPriceStatus() {
        return this.priceStatus;
    }
    
    public void setPriceStatus(String priceStatus) {
        this.priceStatus = priceStatus;
    }
    public Set getGoodses() {
        return this.goodses;
    }
    
    public void setGoodses(Set goodses) {
        this.goodses = goodses;
    }




}


