package com.vasiliskavrn.shop.web.entity;
// Generated Dec 11, 2016 2:21:03 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Producer generated by hbm2java
 */
public class Producer  implements java.io.Serializable {


     private int idProducer;
     private String prodCountry;
     private String prodStatus;
     private Set goodses = new HashSet(0);

    public Producer() {
    }

	
    public Producer(int idProducer) {
        this.idProducer = idProducer;
    }
    public Producer(int idProducer, String prodCountry, String prodStatus, Set goodses) {
       this.idProducer = idProducer;
       this.prodCountry = prodCountry;
       this.prodStatus = prodStatus;
       this.goodses = goodses;
    }
   
    public int getIdProducer() {
        return this.idProducer;
    }
    
    public void setIdProducer(int idProducer) {
        this.idProducer = idProducer;
    }
    public String getProdCountry() {
        return this.prodCountry;
    }
    
    public void setProdCountry(String prodCountry) {
        this.prodCountry = prodCountry;
    }
    public String getProdStatus() {
        return this.prodStatus;
    }
    
    public void setProdStatus(String prodStatus) {
        this.prodStatus = prodStatus;
    }
    public Set getGoodses() {
        return this.goodses;
    }
    
    public void setGoodses(Set goodses) {
        this.goodses = goodses;
    }




}


