package com.vasiliskavrn.shop.web.entity;
// Generated Dec 11, 2016 2:21:03 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Sex generated by hbm2java
 */
public class Sex  implements java.io.Serializable {


     private int idSex;
     private String sexName;
     private String sexStatus;
     private Set goodses = new HashSet(0);

    public Sex() {
    }

	
    public Sex(int idSex) {
        this.idSex = idSex;
    }
    public Sex(int idSex, String sexName, String sexStatus, Set goodses) {
       this.idSex = idSex;
       this.sexName = sexName;
       this.sexStatus = sexStatus;
       this.goodses = goodses;
    }
   
    public int getIdSex() {
        return this.idSex;
    }
    
    public void setIdSex(int idSex) {
        this.idSex = idSex;
    }
    public String getSexName() {
        return this.sexName;
    }
    
    public void setSexName(String sexName) {
        this.sexName = sexName;
    }
    public String getSexStatus() {
        return this.sexStatus;
    }
    
    public void setSexStatus(String sexStatus) {
        this.sexStatus = sexStatus;
    }
    public Set getGoodses() {
        return this.goodses;
    }
    
    public void setGoodses(Set goodses) {
        this.goodses = goodses;
    }




}


