package com.vasiliskavrn.shop.web.entity;
// Generated Dec 11, 2016 2:21:03 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Size generated by hbm2java
 */
public class Size  implements java.io.Serializable {


     private int idSize;
     private String sizeName;
     private String sizeStatus;
     private Set goodses = new HashSet(0);

    public Size() {
    }

	
    public Size(int idSize) {
        this.idSize = idSize;
    }
    public Size(int idSize, String sizeName, String sizeStatus, Set goodses) {
       this.idSize = idSize;
       this.sizeName = sizeName;
       this.sizeStatus = sizeStatus;
       this.goodses = goodses;
    }
   
    public int getIdSize() {
        return this.idSize;
    }
    
    public void setIdSize(int idSize) {
        this.idSize = idSize;
    }
    public String getSizeName() {
        return this.sizeName;
    }
    
    public void setSizeName(String sizeName) {
        this.sizeName = sizeName;
    }
    public String getSizeStatus() {
        return this.sizeStatus;
    }
    
    public void setSizeStatus(String sizeStatus) {
        this.sizeStatus = sizeStatus;
    }
    public Set getGoodses() {
        return this.goodses;
    }
    
    public void setGoodses(Set goodses) {
        this.goodses = goodses;
    }




}


